// Fallback provider list for chat. Runtime provider data normally comes from
// electron/providers/registry.js; this list is used only when IPC loading fails.
export const CHAT_PROVIDERS = [
  { id: 'openai', name: 'OpenAI', platform: 'OpenAI', defaultUrl: 'https://api.openai.com', format: 'openai', defaultModel: 'gpt-5.1', billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'anthropic', name: 'Anthropic', platform: 'Anthropic', defaultUrl: 'https://api.anthropic.com', format: 'anthropic', defaultModel: 'claude-sonnet-4-6', billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { chat: { text: true, thinking: true } } },
  { id: 'google', name: 'Google Gemini', platform: 'Google', defaultUrl: 'https://generativelanguage.googleapis.com', format: 'gemini', defaultModel: 'gemini-2.5-pro', billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { chat: { text: true, multimodal: true } } },
  { id: 'deepseek', name: 'DeepSeek', platform: 'DeepSeek', defaultUrl: 'https://api.deepseek.com', format: 'openai', defaultModel: 'deepseek-chat', billing: { mode: 'paygo' }, meta: { region: 'both' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'alibaba', name: 'Qwen / 通义千问', platform: 'Alibaba Cloud', defaultUrl: 'https://dashscope.aliyuncs.com/compatible-mode', format: 'openai', defaultModel: 'qwen-plus', billing: { mode: 'paygo' }, meta: { region: 'china' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'moonshot', name: 'Kimi / Moonshot', platform: 'Moonshot', defaultUrl: 'https://api.moonshot.cn', format: 'openai', defaultModel: 'kimi-k2-0711-preview', billing: { mode: 'paygo' }, meta: { region: 'china' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'volcengine', name: 'Doubao / 火山方舟', platform: 'Volcengine', defaultUrl: 'https://ark.cn-beijing.volces.com/api/v3', format: 'openai', defaultModel: 'doubao-pro-32k', billing: { mode: 'credits', noteZh: '火山方舟 API 按官方接口计费。' }, meta: { region: 'china', nameZh: '火山方舟', nameEn: 'Volcengine ModelArk', descriptionZh: '火山方舟 API，支持豆包对话。', description: 'Volcengine ModelArk chat API.' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'openrouter', name: 'OpenRouter', platform: 'OpenRouter', defaultUrl: 'https://openrouter.ai/api', format: 'openai', defaultModel: 'openai/gpt-5.1', billing: { mode: 'credits' }, meta: { region: 'global' }, capabilities: { chat: { text: true, openaiCompatible: true, relay: true } } },
  { id: 'groq', name: 'Groq', platform: 'Groq', defaultUrl: 'https://api.groq.com/openai', format: 'openai', defaultModel: 'llama-3.3-70b-versatile', billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'together', name: 'Together AI', platform: 'Together', defaultUrl: 'https://api.together.xyz', format: 'openai', defaultModel: 'meta-llama/Llama-4-17B-128E-Instruct-FP8', billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'xai', name: 'xAI Grok', platform: 'xAI', defaultUrl: 'https://api.x.ai', format: 'openai', defaultModel: 'grok-3', billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'perplexity', name: 'Perplexity', platform: 'Perplexity', defaultUrl: 'https://api.perplexity.ai', format: 'openai', defaultModel: 'sonar-pro', billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { chat: { text: true, search: true, openaiCompatible: true } } },
  { id: 'siliconflow', name: 'SiliconFlow', platform: 'SiliconFlow', defaultUrl: 'https://api.siliconflow.cn', format: 'openai', defaultModel: 'Qwen/Qwen2.5-72B-Instruct', billing: { mode: 'paygo' }, meta: { region: 'china' }, capabilities: { chat: { text: true, openaiCompatible: true } } },
  { id: 'opencode-go', name: 'OpenCode Go', platform: 'OpenCode', defaultUrl: '', format: '', defaultModel: '', integrationStatus: 'metadata', executable: false, billing: { mode: 'subscription', note: 'OpenCode Go subscription setup entry.', noteZh: 'OpenCode Go 订阅资料入口。' }, links: { home: 'https://opencode.ai/', docs: 'https://opencode.ai/docs/go/', pricing: 'https://opencode.ai/docs/go/', purchase: 'https://opencode.ai/docs/go/' }, meta: { region: 'global', nameZh: 'OpenCode Go', nameEn: 'OpenCode Go', description: 'OpenCode Go subscription setup links.', descriptionZh: 'OpenCode Go 订阅资料入口，不作为本应用直连对话接口。' }, capabilities: { chat: { text: true, webSubscription: true, integrationStatus: 'metadata' } } },
  { id: 'volcengine-coding-plan', name: 'Volcengine Coding Plan', platform: 'Volcengine', defaultUrl: 'https://ark.cn-beijing.volces.com/api/v3', format: '', defaultModel: '', integrationStatus: 'metadata', executable: false, billing: { mode: 'subscription', note: 'Volcengine Coding Plan setup entry.', noteZh: '火山方舟编程套餐订阅资料入口。' }, links: { home: 'https://www.volcengine.com/product/ark', docs: 'https://www.volcengine.com/docs/82379/1928261?lang=zh', pricing: 'https://www.volcengine.com/docs/82379/1928261?lang=zh', purchase: 'https://console.volcengine.com/ark' }, meta: { region: 'china', nameZh: '火山方舟编程套餐', nameEn: 'Volcengine Coding Plan', description: 'Volcengine Coding Plan subscription setup links.', descriptionZh: '火山方舟编程套餐订阅资料入口，不作为本应用直连对话接口。' }, capabilities: { chat: { text: true, codingPlan: true, integrationStatus: 'metadata' } } },
  { id: 'chatgpt-plans', name: 'ChatGPT Plus / Pro', platform: 'OpenAI', defaultUrl: '', format: '', defaultModel: '', integrationStatus: 'metadata', executable: false, billing: { mode: 'subscription', note: 'ChatGPT Plus/Pro are web subscriptions, not OpenAI API keys.' }, links: { home: 'https://chatgpt.com/', pricing: 'https://chatgpt.com/pricing/', purchase: 'https://chatgpt.com/pricing/', console: 'https://chatgpt.com/' }, meta: { region: 'global', description: 'ChatGPT web subscription reference.' }, capabilities: { chat: { text: true, webSubscription: true, integrationStatus: 'metadata' } } },
  { id: 'claude-plans', name: 'Claude Pro / Max', platform: 'Anthropic', defaultUrl: '', format: '', defaultModel: '', integrationStatus: 'metadata', executable: false, billing: { mode: 'subscription', note: 'Claude Pro/Max are web subscriptions. Use Anthropic API keys for direct calls.' }, links: { home: 'https://claude.ai/', pricing: 'https://www.anthropic.com/pricing', purchase: 'https://claude.ai/upgrade', console: 'https://claude.ai/' }, meta: { region: 'global', description: 'Claude web subscription reference.' }, capabilities: { chat: { text: true, webSubscription: true, integrationStatus: 'metadata' } } }
]
