// Fallback provider list for video generation. Runtime provider data normally
// comes from electron/providers/registry.js.
export const VID_PROVIDERS = [
  { id: 'volcengine', name: 'Seedance / 即梦', platform: 'Volcengine', defaultUrl: 'https://ark.cn-beijing.volces.com/api/v3', defaultModel: 'doubao-seedance-2-0-pro-250528', protocol: 'ark_video_task', polling: true, billing: { mode: 'credits' }, meta: { region: 'china' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true, modelList: true } } },
  { id: 'alibaba-wan', name: 'Wan / 阿里万相', platform: 'Alibaba Cloud', defaultUrl: 'https://dashscope.aliyuncs.com/api/v1', defaultModel: 'wan2.7-t2v', protocol: 'wan_video_task', polling: true, billing: { mode: 'paygo' }, meta: { region: 'china' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true } } },
  { id: 'runway', name: 'Runway', platform: 'Runway', defaultUrl: 'https://api.dev.runwayml.com', defaultModel: 'gen4_turbo', protocol: 'runway_task', polling: true, billing: { mode: 'credits' }, meta: { region: 'global' }, capabilities: { video: { imageToVideo: true, async: true, polling: true } } },
  { id: 'kling', name: 'Kling AI', platform: 'Kling', defaultUrl: 'https://api-singapore.klingai.com', defaultModel: 'kling-v2.6', protocol: 'kling_video_task', polling: true, integrationStatus: 'metadata', billing: { mode: 'credits' }, meta: { region: 'global' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true } } },
  { id: 'luma', name: 'Luma AI', platform: 'Luma', defaultUrl: 'https://api.lumalabs.ai', defaultModel: 'ray-2', protocol: 'luma_video_task', polling: true, integrationStatus: 'metadata', billing: { mode: 'subscription' }, meta: { region: 'global' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true } } },
  { id: 'minimax', name: 'MiniMax Hailuo', platform: 'MiniMax', defaultUrl: 'https://api.minimax.io', defaultModel: 'MiniMax-Hailuo-2.3', protocol: 'minimax_video_task', polling: true, integrationStatus: 'metadata', billing: { mode: 'subscription' }, meta: { region: 'global' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true } } },
  { id: 'pixverse', name: 'PixVerse', platform: 'PixVerse', defaultUrl: 'https://platform.pixverse.ai', defaultModel: 'pixverse-v6', protocol: 'pixverse_video_task', polling: true, integrationStatus: 'metadata', billing: { mode: 'subscription' }, meta: { region: 'global' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true } } },
  { id: 'fal', name: 'fal', platform: 'fal', defaultUrl: 'https://fal.run', defaultModel: 'fal-ai/wan/v2.5/t2v', protocol: 'fal_video_task', polling: true, integrationStatus: 'metadata', executable: false, billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true, relay: true, modelCatalog: true, integrationStatus: 'metadata' } } },
  { id: 'replicate', name: 'Replicate', platform: 'Replicate', defaultUrl: 'https://api.replicate.com', defaultModel: 'minimax/video-01', protocol: 'replicate_prediction', polling: true, integrationStatus: 'metadata', executable: false, billing: { mode: 'paygo' }, meta: { region: 'global' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true, relay: true, integrationStatus: 'metadata' } } },
  { id: 'baidu-qianfan', name: 'Baidu Qianfan / 百度千帆', platform: 'Baidu', defaultUrl: 'https://qianfan.baidubce.com', defaultModel: 'qianfan-video-latest', protocol: 'baidu_qianfan_video_task', polling: true, billing: { mode: 'paygo' }, meta: { region: 'china' }, capabilities: { video: { textToVideo: true, async: true } } },
  { id: 'tencent-tokenhub', name: 'Tencent Hunyuan / TokenHub', platform: 'Tencent', defaultUrl: 'https://tokenhub.tencentmaas.com/v1/api', defaultModel: 'hy-video-1.5', protocol: 'tencent_tokenhub_video_task', polling: true, billing: { mode: 'paygo' }, meta: { region: 'china' }, capabilities: { video: { textToVideo: true, imageToVideo: true, async: true } } }
]
