import { useCallback, useEffect, useMemo, useState } from 'react'
import Ic from '../icons'
import { TRACKS, selectS, btnS, chipS, SectionHeading, providerDisplayName, localText, StatusBadge, LatencyBadge } from './shared.jsx'

const ICONS = { chat: 'chat', image: 'image', video: 'film' }
const label = (track, lang) => ({ chat: localText(lang, '文本模型', 'Text model'), image: localText(lang, '图片模型', 'Image model'), video: localText(lang, '视频模型', 'Video model') }[track])
function verifiedFor(conn, track) { const validation = conn?.validations?.[track]; const allowed = track === 'chat' ? validation?.status === 'verified' : ['verified', 'directory_verified'].includes(validation?.status); return Boolean(validation?.ok === true && allowed && validation.track === track && validation.inventoryRevision && validation.inventoryRevision === conn.inventoryRevision && validation.inventoryRevision === conn.revision) }
function options(connections, track, lang) { const result = []; for (const conn of connections) { if (!conn.capabilities?.includes(track) || !verifiedFor(conn, track)) continue; for (const model of (conn.models || [])) { if (model.source !== 'remote' || model.capability !== track) continue; result.push({ value: `${conn.id}|${model.id}`, connectionId: conn.id, providerId: conn.providerId, modelId: model.id, label: `${providerDisplayName({ id: conn.providerId, name: conn.name }, lang, track)} · ${model.id}` }) } } return result }

export default function DefaultsPage({ lang, onCanonicalChange, onBusyChange }) {
  const [connections, setConnections] = useState([])
  const [defaults, setDefaults] = useState({ chat: null, image: null, video: null })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => {
    onBusyChange?.(loading || saving)
    return () => onBusyChange?.(false)
  }, [loading, saving, onBusyChange])
  const load = useCallback(async () => { try { const result = await window.electronAPI?.providerConnection?.list(); const canonical = result?.connections || {}; setConnections([...(canonical.accounts || []), ...(canonical.apiKeys || []), ...(canonical.relays || [])]); setDefaults({ chat: canonical.defaults?.chat || null, image: canonical.defaults?.image || null, video: canonical.defaults?.video || null }); onCanonicalChange?.(canonical); setError('') } catch (err) { setError(err?.message || localText(lang, '读取默认模型失败', 'Failed to load defaults')) } finally { setLoading(false) } }, [lang, onCanonicalChange])
  useEffect(() => { load() }, [load])
  const opts = useMemo(() => Object.fromEntries(TRACKS.map(track => [track, options(connections, track, lang)])), [connections, lang])
  const update = async (track, value) => { setDefaults(prev => ({ ...prev, [track]: value })); setSaving(true); setError(''); try { await window.electronAPI?.providerDefaults?.save({ defaults: { [track]: value } }); await load() } catch (err) { setError(err?.message || localText(lang, '默认模型保存失败', 'Failed to save default model')); await load() } finally { setSaving(false) } }
  if (loading) return <div style={{ padding: 24, color: 'var(--text-muted)' }}>{localText(lang, '正在加载…', 'Loading…')}</div>
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}><SectionHeading labelKey="modelPairing" lang={lang} /><div style={{ color: 'var(--text-muted)', fontSize: 12, lineHeight: 1.5 }}>{localText(lang, '只显示已通过真实验证、且来自远端模型目录的能力匹配模型。', 'Only capability-matched models from a current, genuinely verified remote inventory are shown.')}</div>{error && <div style={{ color: 'var(--danger)', fontSize: 12 }}>{error}</div>}{TRACKS.map(track => { const current = defaults[track]; const available = opts[track]; const stale = current && !available.some(item => item.connectionId === current.connectionId && item.modelId === current.modelId); return <div key={track} style={{ border: '1px solid var(--border-default)', borderRadius: 'var(--radius-md)', padding: 14, background: 'var(--bg-surface)' }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 9 }}><Ic n={ICONS[track]} size={14} /><span style={{ fontWeight: 600, color: 'var(--text-primary)', flex: 1 }}>{label(track, lang)}</span>{current && <span style={{ ...chipS(stale ? 'var(--danger)' : 'var(--success)'), fontSize: 10 }}>{stale ? localText(lang, '已失效', 'Stale') : localText(lang, '已设置', 'Set')}</span>}</div>{stale && <div style={{ color: 'var(--danger)', fontSize: 11, marginBottom: 8 }}>{localText(lang, `当前默认模型 ${current.providerId || current.connectionId} · ${current.modelId} 已不在最新远端清单中。可直接清除此项。`, `The current default ${current.providerId || current.connectionId} · ${current.modelId} is missing from the latest remote inventory. Clear it directly.`)}</div>}<div style={{ display: 'flex', gap: 8 }}><select value={current && !stale ? `${current.connectionId}|${current.modelId}` : ''} onChange={e => { const selected = available.find(item => item.value === e.target.value); if (selected) update(track, { connectionId: selected.connectionId, providerId: selected.providerId, modelId: selected.modelId }) }} disabled={saving || available.length === 0} style={{ ...selectS(), flex: 1 }}><option value="">{available.length ? localText(lang, '选择已验证模型', 'Select verified model') : localText(lang, '暂无已验证模型', 'No verified model')}</option>{available.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select>{current && <button onClick={() => update(track, null)} disabled={saving} style={{ ...btnS(false), color: stale ? 'var(--danger)' : 'var(--text-secondary)' }}>{localText(lang, '清除', 'Clear')}</button>}</div></div>})}<div style={{ color: 'var(--text-muted)', fontSize: 11 }}>{localText(lang, '验证状态和模型清单由主进程返回；界面不会凭密钥存在显示成功。', 'Validation status and model inventory come from the main process; a configured key alone never counts as success.')}</div></div>
}
